*Add Soneium Network Support (#26)
Some relevant details:
https://gov.uniswap.org/t/rfc-deploy-uniswap-v2-v3-on-soneium/25413

Still failing to get route:

```sh
error: Failed to get 2 quotes. Reasons: ProviderGasError, ProviderGasError
      at <anonymous> (/Users/bh2smith/Projects/bh2smith/agents/uniswap/node_modules/@uniswap/smart-order-router/build/main/providers/on-chain-quote-provider.js:538:23)
```

Seems a bit like the Uni SDK isn't working yet.


⚠️ This chain has SUPER LOW liquidity

**Only Pools:** (like 10 total)


https://soneium.blockscout.com/address/0x42ae7ec7ff020412639d443e245d936429fbe717?tab=logs

Only a Few with Liquidity:

WETH/ASTR:
https://soneium.blockscout.com/address/0x9d1e91EB341d4E89119EFd370d7B831329c64534

WETH/USDCE:
https://soneium.blockscout.com/address/0xd68e61880190Ebf2bdA21A66d3064625866dDabd

WETH/USDCE:
https://soneium.blockscout.com/address/0xcD4255cEAE51803a9333AA1a559991E17B024eFC


🔴 Depends on https://github.com/BitteProtocol/core/pull/50 (must update
core agent sdk).